[2024-08-17T14:43:09.612+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-17T14:43:10.014+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-15T00:00:00+00:00 [queued]>
[2024-08-17T14:43:10.023+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-15T00:00:00+00:00 [queued]>
[2024-08-17T14:43:10.050+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-17T14:43:10.110+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-15 00:00:00+00:00
[2024-08-17T14:43:10.116+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=515) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T14:43:10.118+0000] {standard_task_runner.py:64} INFO - Started process 520 to run task
[2024-08-17T14:43:10.119+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-15T00:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmprdqlb4m1']
[2024-08-17T14:43:10.122+0000] {standard_task_runner.py:91} INFO - Job 175: Subtask insert_weather_data
[2024-08-17T14:43:10.240+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-15T00:00:00+00:00 [running]> on host 40ce90ebbdd9
[2024-08-17T14:43:10.609+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-15T00:00:00+00:00'
[2024-08-17T14:43:10.611+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-17T14:43:28.543+0000] {logging_mixin.py:188} INFO - Todos los pronósticos han sido insertados con éxito en Redshift.
[2024-08-17T14:43:28.544+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-17T14:43:28.545+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-17T14:43:28.555+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-15T00:00:00+00:00, execution_date=20240815T000000, start_date=20240817T144310, end_date=20240817T144328
[2024-08-17T14:43:28.686+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-17T14:43:28.706+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-17T14:43:28.752+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-05T00:46:54.533+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:46:54.617+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-15T00:00:00+00:00 [queued]>
[2024-09-05T00:46:54.636+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-15T00:00:00+00:00 [queued]>
[2024-09-05T00:46:54.637+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T00:46:54.690+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-15 00:00:00+00:00
[2024-09-05T00:46:54.696+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=772) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:46:54.698+0000] {standard_task_runner.py:72} INFO - Started process 779 to run task
[2024-09-05T00:46:54.699+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-15T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp3b8xf1zi']
[2024-09-05T00:46:54.701+0000] {standard_task_runner.py:105} INFO - Job 88: Subtask insert_weather_data
[2024-09-05T00:46:55.040+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-15T00:00:00+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:46:55.568+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-15T00:00:00+00:00'
[2024-09-05T00:46:55.570+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:46:59.626+0000] {logging_mixin.py:190} INFO - Todos los pronósticos han sido insertados con éxito en Redshift.
[2024-09-05T00:46:59.629+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:46:59.651+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:46:59.654+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-15T00:00:00+00:00, execution_date=20240815T000000, start_date=20240905T004654, end_date=20240905T004659
[2024-09-05T00:47:01.122+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:47:01.205+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:47:01.251+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
