[2024-08-18T00:01:04.415+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-18T00:01:04.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-17T00:00:00+00:00 [queued]>
[2024-08-18T00:01:04.565+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-17T00:00:00+00:00 [queued]>
[2024-08-18T00:01:04.567+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-18T00:01:04.622+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-08-17 00:00:00+00:00
[2024-08-18T00:01:04.627+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=7154) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-18T00:01:04.629+0000] {standard_task_runner.py:64} INFO - Started process 7156 to run task
[2024-08-18T00:01:04.630+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'scheduled__2024-08-17T00:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpedntuv6d']
[2024-08-18T00:01:04.632+0000] {standard_task_runner.py:91} INFO - Job 202: Subtask translate_and_clean_data
[2024-08-18T00:01:04.715+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-17T00:00:00+00:00 [running]> on host b7290fbe53d7
[2024-08-18T00:01:04.871+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-17T00:00:00+00:00'
[2024-08-18T00:01:04.874+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-18T00:01:04.890+0000] {logging_mixin.py:188} INFO - recuperando dataframe de pronosticos desde xcom
[2024-08-18T00:01:04.927+0000] {logging_mixin.py:188} INFO - numero de registros en pronosticos:18
[2024-08-18T00:01:04.964+0000] {logging_mixin.py:188} INFO - Pronósticos antes de limpiar y traducir:    cve_mun            municipio  ... wind_kph  humidity
0        1    AMEALCO DE BONFIL  ...     12.6        82
1        2      PINAL DE AMOLES  ...     20.2        75
2        3          ARROYO SECO  ...     18.7        80
3        4  CADEREYTA DE MONTES  ...     16.9        78
4        5                COLON  ...     20.2        75

[5 rows x 10 columns]
[2024-08-18T00:02:05.186+0000] {logging_mixin.py:188} INFO - Pronósticos después de limpiar y traducir:    cve_mun            municipio  ... viento_kph  humedad
0        1    Amealco De Bonfil  ...       12.6       82
1        2      Pinal De Amoles  ...       20.2       75
2        3          Arroyo Seco  ...       18.7       80
3        4  Cadereyta De Montes  ...       16.9       78
4        5                Colon  ...       20.2       75

[5 rows x 10 columns]
[2024-08-18T00:02:05.253+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-18T00:02:05.256+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-18T00:02:05.268+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=translate_and_clean_data, run_id=scheduled__2024-08-17T00:00:00+00:00, execution_date=20240817T000000, start_date=20240818T000104, end_date=20240818T000205
[2024-08-18T00:02:05.360+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-18T00:02:05.397+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-18T00:02:05.443+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-05T18:16:54.611+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T18:16:54.654+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-17T00:00:00+00:00 [queued]>
[2024-09-05T18:16:54.663+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-17T00:00:00+00:00 [queued]>
[2024-09-05T18:16:54.664+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T18:16:54.782+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-08-17 00:00:00+00:00
[2024-09-05T18:16:54.789+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1020) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T18:16:54.792+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'scheduled__2024-08-17T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp8_x5wrm1']
[2024-09-05T18:16:54.805+0000] {standard_task_runner.py:72} INFO - Started process 1022 to run task
[2024-09-05T18:16:54.805+0000] {standard_task_runner.py:105} INFO - Job 99: Subtask translate_and_clean_data
[2024-09-05T18:16:54.970+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-17T00:00:00+00:00 [running]> on host 0b8eaea5e88c
[2024-09-05T18:16:55.411+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-17T00:00:00+00:00'
[2024-09-05T18:16:55.412+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T18:16:55.425+0000] {logging_mixin.py:190} INFO - Recuperando DataFrame de pronósticos desde XCom
[2024-09-05T18:16:55.466+0000] {logging_mixin.py:190} INFO - Número de registros en pronósticos: 18
[2024-09-05T18:16:55.481+0000] {logging_mixin.py:190} INFO - Pronósticos antes de limpiar y traducir:    cve_mun            municipio  ... wind_kph  humidity
0        1    AMEALCO DE BONFIL  ...     18.0        78
1        2      PINAL DE AMOLES  ...     16.6        75
2        3          ARROYO SECO  ...     17.3        84
3        4  CADEREYTA DE MONTES  ...     14.0        79
4        5                COLON  ...     16.6        75

[5 rows x 10 columns]
[2024-09-05T18:17:55.437+0000] {logging_mixin.py:190} INFO - Pronósticos después de limpiar y traducir:    cve_mun            municipio  ... viento_kph  humedad
0        1    Amealco De Bonfil  ...       18.0       78
1        2      Pinal De Amoles  ...       16.6       75
2        3          Arroyo Seco  ...       17.3       84
3        4  Cadereyta De Montes  ...       14.0       79
4        5                Colon  ...       16.6       75

[5 rows x 10 columns]
[2024-09-05T18:17:56.610+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T18:17:56.936+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T18:17:56.949+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=translate_and_clean_data, run_id=scheduled__2024-08-17T00:00:00+00:00, execution_date=20240817T000000, start_date=20240905T181654, end_date=20240905T181756
[2024-09-05T18:17:58.066+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T18:17:58.890+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T18:17:59.247+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
