[2024-09-05T00:46:29.000+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:46:29.111+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-09-05T00:46:29.157+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-09-05T00:46:29.188+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T00:46:29.280+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-10 00:00:00+00:00
[2024-09-05T00:46:29.350+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=721) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:46:29.363+0000] {standard_task_runner.py:72} INFO - Started process 724 to run task
[2024-09-05T00:46:29.366+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-10T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmptlq7fhfo']
[2024-09-05T00:46:29.373+0000] {standard_task_runner.py:105} INFO - Job 81: Subtask insert_weather_data
[2024-09-05T00:46:30.244+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-10T00:00:00+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:46:32.046+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-10T00:00:00+00:00'
[2024-09-05T00:46:32.047+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:46:36.623+0000] {logging_mixin.py:190} INFO - Todos los pronósticos han sido insertados con éxito en Redshift.
[2024-09-05T00:46:36.626+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:46:36.678+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:46:36.687+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-10T00:00:00+00:00, execution_date=20240810T000000, start_date=20240905T004629, end_date=20240905T004636
[2024-09-05T00:46:37.366+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:46:37.456+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:46:37.501+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-09-05T18:15:17.826+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T18:15:17.965+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-09-05T18:15:18.087+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-09-05T18:15:18.087+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T18:15:18.223+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-10 00:00:00+00:00
[2024-09-05T18:15:18.229+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=770) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T18:15:18.232+0000] {standard_task_runner.py:72} INFO - Started process 774 to run task
[2024-09-05T18:15:18.238+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-10T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp9omajxuv']
[2024-09-05T18:15:18.242+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask insert_weather_data
[2024-09-05T18:15:18.367+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-10T00:00:00+00:00 [running]> on host 0b8eaea5e88c
[2024-09-05T18:15:18.834+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-10T00:00:00+00:00'
[2024-09-05T18:15:18.836+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T18:15:19.846+0000] {logging_mixin.py:190} INFO - Ya existe un registro para la fecha de hoy. Finalizando tarea.
[2024-09-05T18:15:19.912+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T18:15:19.936+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T18:15:19.967+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-10T00:00:00+00:00, execution_date=20240810T000000, start_date=20240905T181518, end_date=20240905T181519
[2024-09-05T18:15:20.131+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T18:15:20.254+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T18:15:20.346+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
