[2024-08-15T00:03:25.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-15T00:03:25.498+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-14T00:00:00+00:00 [queued]>
[2024-08-15T00:03:25.511+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-14T00:00:00+00:00 [queued]>
[2024-08-15T00:03:25.513+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-15T00:03:25.605+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_forecast_and_drought_data> on 2024-08-14 00:00:00+00:00
[2024-08-15T00:03:25.611+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1700) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-15T00:03:25.613+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_forecast_and_drought_data', 'scheduled__2024-08-14T00:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmplcagkpib']
[2024-08-15T00:03:25.619+0000] {standard_task_runner.py:91} INFO - Job 160: Subtask get_forecast_and_drought_data
[2024-08-15T00:03:25.619+0000] {standard_task_runner.py:64} INFO - Started process 1702 to run task
[2024-08-15T00:03:25.710+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-14T00:00:00+00:00 [running]> on host 6da407953da9
[2024-08-15T00:03:25.891+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_forecast_and_drought_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-14T00:00:00+00:00'
[2024-08-15T00:03:25.893+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-15T00:03:26.516+0000] {warnings.py:112} WARNING - /opt/***/dags/weather_etl_dag.py:249: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_pronosticos_clima = pd.read_sql_query(query, conn)

[2024-08-15T00:03:26.705+0000] {warnings.py:112} WARNING - /opt/***/dags/weather_etl_dag.py:253: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sequia = pd.read_sql_query(query, conn)

[2024-08-15T00:03:27.202+0000] {logging_mixin.py:188} INFO - Pronósticos clima obtenidos:    cve_mun            municipio fecha_pronostico indicador_sequia
0        1    Amealco De Bonfil       2024-08-14             None
1        2      Pinal De Amoles       2024-08-14             None
2        3          Arroyo Seco       2024-08-14             None
3        4  Cadereyta De Montes       2024-08-14             None
4        5                Colon       2024-08-14             None
[2024-08-15T00:03:27.214+0000] {logging_mixin.py:188} INFO - Datos de sequía obtenidos:    cve_mun          nombre_mun  cve_ent               entidad       fecha valor
0        1   Amealco de Bonfil       22  Querétaro de Arteaga  2003-03-31    D0
1       10  Landa de Matamoros       22  Querétaro de Arteaga  2003-06-30    D0
2        2     Pinal de Amoles       22  Querétaro de Arteaga  2004-09-30    D0
3        3         Arroyo Seco       22  Querétaro de Arteaga  2004-09-30    D0
4        9     Jalpan de Serra       22  Querétaro de Arteaga  2004-09-30    D0
[2024-08-15T00:03:27.342+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-15T00:03:27.349+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-15T00:03:27.359+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_forecast_and_drought_data, run_id=scheduled__2024-08-14T00:00:00+00:00, execution_date=20240814T000000, start_date=20240815T000325, end_date=20240815T000327
[2024-08-15T00:03:27.444+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-15T00:03:27.486+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-15T00:03:27.533+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-05T00:47:41.714+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:47:41.763+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-14T00:00:00+00:00 [queued]>
[2024-09-05T00:47:41.772+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-14T00:00:00+00:00 [queued]>
[2024-09-05T00:47:41.773+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T00:47:41.840+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_forecast_and_drought_data> on 2024-08-14 00:00:00+00:00
[2024-09-05T00:47:41.850+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=872) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:47:41.854+0000] {standard_task_runner.py:72} INFO - Started process 874 to run task
[2024-09-05T00:47:41.857+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_forecast_and_drought_data', 'scheduled__2024-08-14T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmprc5dmz3o']
[2024-09-05T00:47:41.863+0000] {standard_task_runner.py:105} INFO - Job 102: Subtask get_forecast_and_drought_data
[2024-09-05T00:47:42.048+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-14T00:00:00+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:47:42.513+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_forecast_and_drought_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-14T00:00:00+00:00'
[2024-09-05T00:47:42.515+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:47:43.142+0000] {warnings.py:112} WARNING - /root/***/dags/weather_etl.py:163: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_pronosticos_clima = pd.read_sql_query(query, conn)

[2024-09-05T00:47:43.361+0000] {warnings.py:112} WARNING - /root/***/dags/weather_etl.py:167: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sequia = pd.read_sql_query(query, conn)

[2024-09-05T00:47:43.746+0000] {logging_mixin.py:190} INFO - Pronósticos clima obtenidos:    cve_mun            municipio fecha_pronostico indicador_sequia
0        1    Amealco De Bonfil       2024-09-04             None
1        2      Pinal De Amoles       2024-09-04             None
2        3          Arroyo Seco       2024-09-04             None
3        4  Cadereyta De Montes       2024-09-04             None
4        5                Colon       2024-09-04             None
[2024-09-05T00:47:43.764+0000] {logging_mixin.py:190} INFO - Datos de sequía obtenidos:    cve_mun          nombre_mun  cve_ent               entidad       fecha valor
0        1   Amealco de Bonfil       22  Querétaro de Arteaga  2003-03-31    D0
1       10  Landa de Matamoros       22  Querétaro de Arteaga  2003-06-30    D0
2        2     Pinal de Amoles       22  Querétaro de Arteaga  2004-09-30    D0
3        3         Arroyo Seco       22  Querétaro de Arteaga  2004-09-30    D0
4        9     Jalpan de Serra       22  Querétaro de Arteaga  2004-09-30    D0
[2024-09-05T00:47:43.957+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:47:43.997+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:47:43.998+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_forecast_and_drought_data, run_id=scheduled__2024-08-14T00:00:00+00:00, execution_date=20240814T000000, start_date=20240905T004741, end_date=20240905T004743
[2024-09-05T00:47:44.099+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:47:44.171+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:47:44.221+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
