[2024-08-17T14:43:09.188+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-17T14:43:09.780+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-08-17T14:43:09.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-08-17T14:43:09.816+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-17T14:43:10.048+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-16 00:00:00+00:00
[2024-08-17T14:43:10.057+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=516) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T14:43:10.059+0000] {standard_task_runner.py:64} INFO - Started process 519 to run task
[2024-08-17T14:43:10.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-16T00:00:00+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpeqq6yjxg']
[2024-08-17T14:43:10.079+0000] {standard_task_runner.py:91} INFO - Job 174: Subtask insert_weather_data
[2024-08-17T14:43:10.184+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-16T00:00:00+00:00 [running]> on host 40ce90ebbdd9
[2024-08-17T14:43:10.451+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-16T00:00:00+00:00'
[2024-08-17T14:43:10.467+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-17T14:43:30.577+0000] {logging_mixin.py:188} INFO - Todos los pronósticos han sido insertados con éxito en Redshift.
[2024-08-17T14:43:30.579+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-17T14:43:30.580+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-17T14:43:30.594+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-16T00:00:00+00:00, execution_date=20240816T000000, start_date=20240817T144309, end_date=20240817T144330
[2024-08-17T14:43:32.618+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-17T14:43:32.650+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-17T14:43:33.008+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-05T18:19:19.576+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T18:19:19.671+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-09-05T18:19:19.739+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-09-05T18:19:19.740+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T18:19:19.855+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-16 00:00:00+00:00
[2024-09-05T18:19:19.859+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1146) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T18:19:19.861+0000] {standard_task_runner.py:72} INFO - Started process 1150 to run task
[2024-09-05T18:19:19.862+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-16T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmppin5y621']
[2024-09-05T18:19:19.864+0000] {standard_task_runner.py:105} INFO - Job 114: Subtask insert_weather_data
[2024-09-05T18:19:19.968+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-16T00:00:00+00:00 [running]> on host 0b8eaea5e88c
[2024-09-05T18:19:20.759+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-16T00:00:00+00:00'
[2024-09-05T18:19:20.761+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T18:19:21.702+0000] {logging_mixin.py:190} INFO - Ya existe un registro para la fecha de hoy. Finalizando tarea.
[2024-09-05T18:19:21.785+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T18:19:21.830+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T18:19:21.831+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-16T00:00:00+00:00, execution_date=20240816T000000, start_date=20240905T181919, end_date=20240905T181921
[2024-09-05T18:19:21.967+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T18:19:22.043+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T18:19:22.144+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
