[2024-08-14T00:20:46.592+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T00:20:46.732+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data manual__2024-08-14T00:18:41.299582+00:00 [queued]>
[2024-08-14T00:20:46.781+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data manual__2024-08-14T00:18:41.299582+00:00 [queued]>
[2024-08-14T00:20:46.930+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-14T00:20:51.970+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-08-14 00:18:41.299582+00:00
[2024-08-14T00:20:51.977+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=5102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T00:20:51.979+0000] {standard_task_runner.py:64} INFO - Started process 5123 to run task
[2024-08-14T00:20:51.979+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'manual__2024-08-14T00:18:41.299582+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp3fngxw39']
[2024-08-14T00:20:51.982+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask translate_and_clean_data
[2024-08-14T00:20:52.088+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data manual__2024-08-14T00:18:41.299582+00:00 [running]> on host 68978d07c676
[2024-08-14T00:20:52.835+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:18:41.299582+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T00:18:41.299582+00:00'
[2024-08-14T00:20:52.840+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T00:22:00.216+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T00:22:00.217+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T00:22:00.226+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=translate_and_clean_data, run_id=manual__2024-08-14T00:18:41.299582+00:00, execution_date=20240814T001841, start_date=20240814T002046, end_date=20240814T002200
[2024-08-14T00:22:00.554+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-14T00:22:00.575+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T00:22:00.758+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
