[2024-09-05T00:46:22.846+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:46:22.881+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-09T00:00:00+00:00 [queued]>
[2024-09-05T00:46:22.897+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-09T00:00:00+00:00 [queued]>
[2024-09-05T00:46:22.899+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T00:46:22.957+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-09 00:00:00+00:00
[2024-09-05T00:46:22.967+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=714) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:46:22.970+0000] {standard_task_runner.py:72} INFO - Started process 716 to run task
[2024-09-05T00:46:22.970+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-09T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmppal6428m']
[2024-09-05T00:46:22.973+0000] {standard_task_runner.py:105} INFO - Job 80: Subtask insert_weather_data
[2024-09-05T00:46:23.106+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-09T00:00:00+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:46:23.558+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-09T00:00:00+00:00'
[2024-09-05T00:46:23.562+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:46:27.965+0000] {logging_mixin.py:190} INFO - Todos los pronósticos han sido insertados con éxito en Redshift.
[2024-09-05T00:46:27.970+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:46:28.024+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:46:28.026+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-09T00:00:00+00:00, execution_date=20240809T000000, start_date=20240905T004622, end_date=20240905T004628
[2024-09-05T00:46:28.560+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:46:28.681+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:46:28.720+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-09-05T18:15:17.466+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T18:15:17.553+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-09T00:00:00+00:00 [queued]>
[2024-09-05T18:15:17.568+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-09T00:00:00+00:00 [queued]>
[2024-09-05T18:15:17.569+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T18:15:17.749+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-09 00:00:00+00:00
[2024-09-05T18:15:17.763+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=768) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T18:15:17.766+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-09T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpnc1zxezj']
[2024-09-05T18:15:17.806+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask insert_weather_data
[2024-09-05T18:15:17.805+0000] {standard_task_runner.py:72} INFO - Started process 772 to run task
[2024-09-05T18:15:18.084+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-09T00:00:00+00:00 [running]> on host 0b8eaea5e88c
[2024-09-05T18:15:18.581+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-09T00:00:00+00:00'
[2024-09-05T18:15:18.582+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T18:15:19.472+0000] {logging_mixin.py:190} INFO - Ya existe un registro para la fecha de hoy. Finalizando tarea.
[2024-09-05T18:15:19.543+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T18:15:19.572+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T18:15:19.575+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-09T00:00:00+00:00, execution_date=20240809T000000, start_date=20240905T181517, end_date=20240905T181519
[2024-09-05T18:15:19.712+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T18:15:19.767+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T18:15:19.817+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
