[2024-09-05T00:46:14.706+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:46:14.752+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-07T00:00:00+00:00 [queued]>
[2024-09-05T00:46:14.783+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-07T00:00:00+00:00 [queued]>
[2024-09-05T00:46:14.785+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T00:46:14.885+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-07 00:00:00+00:00
[2024-09-05T00:46:14.894+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=700) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:46:14.896+0000] {standard_task_runner.py:72} INFO - Started process 702 to run task
[2024-09-05T00:46:14.897+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-07T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpmchvload']
[2024-09-05T00:46:14.900+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask insert_weather_data
[2024-09-05T00:46:15.456+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-07T00:00:00+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:46:16.366+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-07T00:00:00+00:00'
[2024-09-05T00:46:16.369+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:46:20.826+0000] {logging_mixin.py:190} INFO - Todos los pronósticos han sido insertados con éxito en Redshift.
[2024-09-05T00:46:20.832+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:46:20.878+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:46:20.886+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-07T00:00:00+00:00, execution_date=20240807T000000, start_date=20240905T004614, end_date=20240905T004620
[2024-09-05T00:46:21.013+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:46:21.126+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:46:21.167+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-09-05T18:15:05.900+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T18:15:05.972+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-07T00:00:00+00:00 [queued]>
[2024-09-05T18:15:05.983+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-07T00:00:00+00:00 [queued]>
[2024-09-05T18:15:05.984+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T18:15:06.044+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-07 00:00:00+00:00
[2024-09-05T18:15:06.053+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T18:15:06.062+0000] {standard_task_runner.py:72} INFO - Started process 745 to run task
[2024-09-05T18:15:06.060+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-07T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmppk9_zr_h']
[2024-09-05T18:15:06.066+0000] {standard_task_runner.py:105} INFO - Job 59: Subtask insert_weather_data
[2024-09-05T18:15:06.261+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-07T00:00:00+00:00 [running]> on host 0b8eaea5e88c
[2024-09-05T18:15:07.355+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-07T00:00:00+00:00'
[2024-09-05T18:15:07.358+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T18:15:08.128+0000] {logging_mixin.py:190} INFO - Ya existe un registro para la fecha de hoy. Finalizando tarea.
[2024-09-05T18:15:08.200+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T18:15:08.222+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T18:15:08.223+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-07T00:00:00+00:00, execution_date=20240807T000000, start_date=20240905T181505, end_date=20240905T181508
[2024-09-05T18:15:08.414+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T18:15:08.442+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T18:15:08.513+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
