[2024-08-17T14:41:56.464+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-17T14:41:56.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-08-17T14:41:56.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-08-17T14:41:56.748+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-17T14:41:56.862+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-08-16 00:00:00+00:00
[2024-08-17T14:41:56.871+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=489) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T14:41:56.873+0000] {standard_task_runner.py:64} INFO - Started process 493 to run task
[2024-08-17T14:41:56.878+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'scheduled__2024-08-16T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmprhpr4qxt']
[2024-08-17T14:41:56.880+0000] {standard_task_runner.py:91} INFO - Job 172: Subtask translate_and_clean_data
[2024-08-17T14:41:57.003+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-16T00:00:00+00:00 [running]> on host 40ce90ebbdd9
[2024-08-17T14:41:57.200+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-16T00:00:00+00:00'
[2024-08-17T14:41:57.201+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-17T14:41:57.215+0000] {logging_mixin.py:188} INFO - recuperando dataframe de pronosticos desde xcom
[2024-08-17T14:41:57.297+0000] {logging_mixin.py:188} INFO - numero de registros en pronosticos:18
[2024-08-17T14:41:57.453+0000] {logging_mixin.py:188} INFO - Pronósticos antes de limpiar y traducir:    cve_mun            municipio  ... wind_kph  humidity
0        1    AMEALCO DE BONFIL  ...     14.8        80
1        2      PINAL DE AMOLES  ...     18.0        78
2        3          ARROYO SECO  ...     13.3        82
3        4  CADEREYTA DE MONTES  ...     16.2        79
4        5                COLON  ...     18.0        78

[5 rows x 10 columns]
[2024-08-17T14:42:58.984+0000] {logging_mixin.py:188} INFO - Pronósticos después de limpiar y traducir:    cve_mun            municipio  ... viento_kph  humedad
0        1    Amealco De Bonfil  ...       14.8       80
1        2      Pinal De Amoles  ...       18.0       78
2        3          Arroyo Seco  ...       13.3       82
3        4  Cadereyta De Montes  ...       16.2       79
4        5                Colon  ...       18.0       78

[5 rows x 10 columns]
[2024-08-17T14:43:00.654+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-17T14:43:00.663+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-17T14:43:00.742+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=translate_and_clean_data, run_id=scheduled__2024-08-16T00:00:00+00:00, execution_date=20240816T000000, start_date=20240817T144156, end_date=20240817T144300
[2024-08-17T14:43:00.912+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-17T14:43:02.320+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-17T14:43:02.689+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-05T18:16:51.727+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T18:16:51.778+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-09-05T18:16:51.800+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-16T00:00:00+00:00 [queued]>
[2024-09-05T18:16:51.808+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T18:16:51.889+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-08-16 00:00:00+00:00
[2024-09-05T18:16:51.949+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1007) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T18:16:51.951+0000] {standard_task_runner.py:72} INFO - Started process 1012 to run task
[2024-09-05T18:16:51.952+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'scheduled__2024-08-16T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp43edkbuh']
[2024-09-05T18:16:51.967+0000] {standard_task_runner.py:105} INFO - Job 98: Subtask translate_and_clean_data
[2024-09-05T18:16:52.351+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-16T00:00:00+00:00 [running]> on host 0b8eaea5e88c
[2024-09-05T18:16:53.282+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-16T00:00:00+00:00'
[2024-09-05T18:16:53.283+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T18:16:53.301+0000] {logging_mixin.py:190} INFO - Recuperando DataFrame de pronósticos desde XCom
[2024-09-05T18:16:53.448+0000] {logging_mixin.py:190} INFO - Número de registros en pronósticos: 18
[2024-09-05T18:16:53.470+0000] {logging_mixin.py:190} INFO - Pronósticos antes de limpiar y traducir:    cve_mun            municipio  ... wind_kph  humidity
0        1    AMEALCO DE BONFIL  ...     18.0        78
1        2      PINAL DE AMOLES  ...     16.6        75
2        3          ARROYO SECO  ...     17.3        84
3        4  CADEREYTA DE MONTES  ...     14.0        79
4        5                COLON  ...     16.6        75

[5 rows x 10 columns]
[2024-09-05T18:17:53.257+0000] {logging_mixin.py:190} INFO - Pronósticos después de limpiar y traducir:    cve_mun            municipio  ... viento_kph  humedad
0        1    Amealco De Bonfil  ...       18.0       78
1        2      Pinal De Amoles  ...       16.6       75
2        3          Arroyo Seco  ...       17.3       84
3        4  Cadereyta De Montes  ...       14.0       79
4        5                Colon  ...       16.6       75

[5 rows x 10 columns]
[2024-09-05T18:17:53.952+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T18:17:54.003+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T18:17:54.004+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=translate_and_clean_data, run_id=scheduled__2024-08-16T00:00:00+00:00, execution_date=20240816T000000, start_date=20240905T181651, end_date=20240905T181754
[2024-09-05T18:17:54.317+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T18:17:54.488+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T18:17:54.660+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
