[2024-09-05T00:40:14.385+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:40:14.663+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-09-05T00:40:14.815+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-09-05T00:40:14.835+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T00:40:15.090+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-03 00:00:00+00:00
[2024-09-05T00:40:15.169+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=501) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:40:15.334+0000] {standard_task_runner.py:72} INFO - Started process 505 to run task
[2024-09-05T00:40:15.336+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-03T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmppob5rnvu']
[2024-09-05T00:40:15.729+0000] {standard_task_runner.py:105} INFO - Job 59: Subtask insert_weather_data
[2024-09-05T00:40:16.222+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-03T00:00:00+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:40:17.621+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-03T00:00:00+00:00'
[2024-09-05T00:40:17.627+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:40:23.824+0000] {logging_mixin.py:190} INFO - Todos los pronósticos han sido insertados con éxito en Redshift.
[2024-09-05T00:40:23.836+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:40:23.964+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:40:23.983+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-03T00:00:00+00:00, execution_date=20240803T000000, start_date=20240905T004014, end_date=20240905T004023
[2024-09-05T00:40:24.115+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:40:24.211+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:40:24.355+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-09-05T18:14:47.864+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T18:14:47.995+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-09-05T18:14:48.009+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-09-05T18:14:48.009+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T18:14:48.147+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-03 00:00:00+00:00
[2024-09-05T18:14:48.152+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=700) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T18:14:48.155+0000] {standard_task_runner.py:72} INFO - Started process 702 to run task
[2024-09-05T18:14:48.155+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'scheduled__2024-08-03T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpaxm9y9bb']
[2024-09-05T18:14:48.158+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask insert_weather_data
[2024-09-05T18:14:48.298+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data scheduled__2024-08-03T00:00:00+00:00 [running]> on host 0b8eaea5e88c
[2024-09-05T18:14:48.603+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-03T00:00:00+00:00'
[2024-09-05T18:14:48.605+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T18:14:49.414+0000] {logging_mixin.py:190} INFO - Ya existe un registro para la fecha de hoy. Finalizando tarea.
[2024-09-05T18:14:49.482+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T18:14:49.496+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T18:14:49.497+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=scheduled__2024-08-03T00:00:00+00:00, execution_date=20240803T000000, start_date=20240905T181447, end_date=20240905T181449
[2024-09-05T18:14:49.621+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T18:14:49.660+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T18:14:49.697+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
