[2024-09-05T00:47:11.007+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:47:11.119+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-09-05T00:47:11.148+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-09-05T00:47:11.171+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T00:47:11.318+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_forecast_and_drought_data> on 2024-08-06 00:00:00+00:00
[2024-09-05T00:47:11.327+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_forecast_and_drought_data', 'scheduled__2024-08-06T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp7526vu_j']
[2024-09-05T00:47:11.347+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=805) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:47:11.355+0000] {standard_task_runner.py:105} INFO - Job 93: Subtask get_forecast_and_drought_data
[2024-09-05T00:47:11.355+0000] {standard_task_runner.py:72} INFO - Started process 816 to run task
[2024-09-05T00:47:11.966+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-06T00:00:00+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:47:12.807+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_forecast_and_drought_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-06T00:00:00+00:00'
[2024-09-05T00:47:12.821+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:47:13.834+0000] {warnings.py:112} WARNING - /root/***/dags/weather_etl.py:163: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_pronosticos_clima = pd.read_sql_query(query, conn)

[2024-09-05T00:47:14.049+0000] {warnings.py:112} WARNING - /root/***/dags/weather_etl.py:167: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sequia = pd.read_sql_query(query, conn)

[2024-09-05T00:47:14.534+0000] {logging_mixin.py:190} INFO - Pronósticos clima obtenidos:    cve_mun            municipio fecha_pronostico indicador_sequia
0        1    Amealco De Bonfil       2024-09-04             None
1        2      Pinal De Amoles       2024-09-04             None
2        3          Arroyo Seco       2024-09-04             None
3        4  Cadereyta De Montes       2024-09-04             None
4        5                Colon       2024-09-04             None
[2024-09-05T00:47:14.572+0000] {logging_mixin.py:190} INFO - Datos de sequía obtenidos:    cve_mun          nombre_mun  cve_ent               entidad       fecha valor
0        1   Amealco de Bonfil       22  Querétaro de Arteaga  2003-03-31    D0
1       10  Landa de Matamoros       22  Querétaro de Arteaga  2003-06-30    D0
2        2     Pinal de Amoles       22  Querétaro de Arteaga  2004-09-30    D0
3        3         Arroyo Seco       22  Querétaro de Arteaga  2004-09-30    D0
4        9     Jalpan de Serra       22  Querétaro de Arteaga  2004-09-30    D0
[2024-09-05T00:47:16.503+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:47:16.545+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:47:16.560+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_forecast_and_drought_data, run_id=scheduled__2024-08-06T00:00:00+00:00, execution_date=20240806T000000, start_date=20240905T004711, end_date=20240905T004716
[2024-09-05T00:47:16.947+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:47:17.061+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:47:17.107+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-09-05T18:15:40.986+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T18:15:41.040+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-09-05T18:15:41.050+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-09-05T18:15:41.051+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T18:15:41.152+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_forecast_and_drought_data> on 2024-08-06 00:00:00+00:00
[2024-09-05T18:15:41.157+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=830) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T18:15:41.161+0000] {standard_task_runner.py:72} INFO - Started process 834 to run task
[2024-09-05T18:15:41.163+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_forecast_and_drought_data', 'scheduled__2024-08-06T00:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpjg368w40']
[2024-09-05T18:15:41.165+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask get_forecast_and_drought_data
[2024-09-05T18:15:41.417+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.get_forecast_and_drought_data scheduled__2024-08-06T00:00:00+00:00 [running]> on host 0b8eaea5e88c
[2024-09-05T18:15:42.177+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_forecast_and_drought_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-06T00:00:00+00:00'
[2024-09-05T18:15:42.201+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T18:15:43.062+0000] {warnings.py:112} WARNING - /root/***/dags/weather_etl.py:163: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_pronosticos_clima = pd.read_sql_query(query, conn)

[2024-09-05T18:15:43.201+0000] {warnings.py:112} WARNING - /root/***/dags/weather_etl.py:167: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sequia = pd.read_sql_query(query, conn)

[2024-09-05T18:15:43.625+0000] {logging_mixin.py:190} INFO - Pronósticos clima obtenidos:    cve_mun            municipio fecha_pronostico indicador_sequia
0        1    Amealco De Bonfil       2024-09-05             None
1        2      Pinal De Amoles       2024-09-05             None
2        3          Arroyo Seco       2024-09-05             None
3        4  Cadereyta De Montes       2024-09-05             None
4        5                Colon       2024-09-05             None
[2024-09-05T18:15:43.631+0000] {logging_mixin.py:190} INFO - Datos de sequía obtenidos:    cve_mun          nombre_mun  cve_ent               entidad       fecha valor
0        1   Amealco de Bonfil       22  Querétaro de Arteaga  2003-03-31    D0
1       10  Landa de Matamoros       22  Querétaro de Arteaga  2003-06-30    D0
2        2     Pinal de Amoles       22  Querétaro de Arteaga  2004-09-30    D0
3        3         Arroyo Seco       22  Querétaro de Arteaga  2004-09-30    D0
4        9     Jalpan de Serra       22  Querétaro de Arteaga  2004-09-30    D0
[2024-09-05T18:15:45.603+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T18:15:45.678+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T18:15:45.681+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_forecast_and_drought_data, run_id=scheduled__2024-08-06T00:00:00+00:00, execution_date=20240806T000000, start_date=20240905T181541, end_date=20240905T181545
[2024-09-05T18:15:45.834+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T18:15:45.963+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T18:15:46.019+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
